version = 1

[[annotations]]
path = [
    "REUSE.toml",
    "README.md",
    "crowdin.yml",
    ".gitmodules",
	"src/shadLauncher4.rc",
	"src/shadLauncher4.qrc",
	"src/images/shadLauncher4.ico",
    "src/images/shadLauncher4.png",
    "src/images/grid.png",
    "src/images/list.png",
    "src/images/refresh.png",
    "src/images/play.png",
    "src/images/stop.png",
    "src/images/settings.png",
    "src/images/fullscreen.png",
    "src/images/controllers.png",
    "src/images/restart.png",
    "src/images/pause.png",
	"src/images/flag_china.png",
    "src/images/flag_eu.png",
    "src/images/flag_jp.png",
    "src/images/flag_unk.png",
    "src/images/flag_us.png",
    "src/images/flag_world.png",
    "src/qt_ui/settings_dialog.ui",
    "src/qt_ui/game_install_dialog.ui",
    "src/qt_ui/cheats_patches_dialog.ui"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "shadLauncher4 Project"
SPDX-License-Identifier = "GPL-2.0-or-later"

